version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env

  node_app:
    image: node
    # baixando no docker hub nâo precisa do dockerFile né
    container_name: node_app
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
